-- ============================================================
-- 004: 마이그레이션 전 IDENTITY 컬럼 수정
-- GENERATED ALWAYS → GENERATED BY DEFAULT (명시적 ID 삽입 허용)
-- 마이그레이션 스크립트 실행 전에 Supabase SQL Editor에서 실행
-- ============================================================

-- organ: org_id
ALTER TABLE organ ALTER COLUMN org_id SET GENERATED BY DEFAULT;

-- customer: cust_id
ALTER TABLE customer ALTER COLUMN cust_id SET GENERATED BY DEFAULT;

-- acc_book: acc_book_id
ALTER TABLE acc_book ALTER COLUMN acc_book_id SET GENERATED BY DEFAULT;

-- acc_book_bak: bak_id
ALTER TABLE acc_book_bak ALTER COLUMN bak_id SET GENERATED BY DEFAULT;

-- estate: estate_id
ALTER TABLE estate ALTER COLUMN estate_id SET GENERATED BY DEFAULT;

-- acc_rel: acc_rel_id
ALTER TABLE acc_rel ALTER COLUMN acc_rel_id SET GENERATED BY DEFAULT;

-- user_organ: id
ALTER TABLE user_organ ALTER COLUMN id SET GENERATED BY DEFAULT;

-- backup_history: id
ALTER TABLE backup_history ALTER COLUMN id SET GENERATED BY DEFAULT;

-- col_organ: id
ALTER TABLE col_organ ALTER COLUMN id SET GENERATED BY DEFAULT;

-- sum_rept: sum_rept_id
ALTER TABLE sum_rept ALTER COLUMN sum_rept_id SET GENERATED BY DEFAULT;

-- 확인
SELECT table_name, column_name, identity_generation
FROM information_schema.columns
WHERE table_schema = 'public'
  AND identity_generation IS NOT NULL
ORDER BY table_name, column_name;
